[package]
name = "minecraft_tracker"
version = "0.1.0"
authors = ["Brandon Atkinson <bj.atkinson92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
colored = "2"
